export const UserList = [
  {
    id: 1,
    name: "John Doe",
    username: "johndoe123",
    age: 30,
    nationality: "USA",
  },
  {
    id: 2,
    name: "Jane Smith",
    username: "janesmith456",
    age: 25,
    nationality: "Canada",
  },
  {
    id: 3,
    name: "Michael Johnson",
    username: "mikej",
    age: 28,
    nationality: "UK",
  },
  {
    id: 4,
    name: "Maria Garcia",
    username: "mariag",
    age: 32,
    nationality: "Spain",
  },
  {
    id: 5,
    name: "Mohammed Ali",
    username: "mali",
    age: 27,
    nationality: "Egypt",
  },
  {
    id: 6,
    name: "Luisa Silva",
    username: "luisas",
    age: 29,
    nationality: "Brazil",
  },
  {
    id: 7,
    name: "Kim Lee",
    username: "kiml",
    age: 26,
    nationality: "South Korea",
  },
  {
    id: 8,
    name: "Andrea Rossi",
    username: "andrear",
    age: 31,
    nationality: "Italy",
  },
  {
    id: 9,
    name: "Hiroshi Tanaka",
    username: "hiroshit",
    age: 33,
    nationality: "Japan",
  },
  {
    id: 10,
    name: "Marta Hernandez",
    username: "martah",
    age: 28,
    nationality: "Mexico",
  },
  {
    id: 11,
    name: "Anna Petrov",
    username: "annap",
    age: 29,
    nationality: "Russia",
  },
  {
    id: 12,
    name: "Juan Lopez",
    username: "juanl",
    age: 35,
    nationality: "Argentina",
  },
  {
    id: 13,
    name: "Chen Wei",
    username: "chenw",
    age: 27,
    nationality: "China",
  },
  {
    id: 14,
    name: "Fatemeh Azizi",
    username: "fatemeha",
    age: 26,
    nationality: "Iran",
  },
  {
    id: 15,
    name: "Marta Gonzalez",
    username: "martag",
    age: 30,
    nationality: "Spain",
  },
  {
    id: 16,
    name: "Sergei Ivanov",
    username: "sergeii",
    age: 32,
    nationality: "Russia",
  },
  {
    id: 17,
    name: "Fatima Khan",
    username: "fatimak",
    age: 29,
    nationality: "Pakistan",
  },
  {
    id: 18,
    name: "Carlos Ramirez",
    username: "carlosr",
    age: 28,
    nationality: "Mexico",
  },
  {
    id: 19,
    name: "Aisha Ahmed",
    username: "aishaa",
    age: 27,
    nationality: "Saudi Arabia",
  },
  {
    id: 20,
    name: "Sophie Dupont",
    username: "sophied",
    age: 31,
    nationality: "France",
  },
];
